version: "3"

services:
  live:
    image: live:0.1
    expose:
      - 8558
      - 2552
      - 8080
      - 9090
    environment:
      - ENV=discovery

  gateway:
    image: quay.io/datawire/ambassador:0.85.0
    ports:
      - 9900:8080
      - 9901:8877
    environment:
      - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
    volumes:
      - $PWD/ambassador.yaml:/ambassador/ambassador-config/ambassador.yaml
