---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: live
  namespace: live
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: live
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: live
subjects:
  - kind: ServiceAccount
    name: live
roleRef:
  kind: Role
  name: read-pods
  apiGroup: rbac.authorization.k8s.io