---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    enable_grpc_web: true
    cors:
      origins: "*"
      methods: GET, PUT, DELETE, POST, OPTIONS
      headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
      exposed_headers: custom-header-1,grpc-status,grpc-message
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: ambassador
---
apiVersion: v1
kind: Service
metadata:
  name: live
spec:
  ports:
    - name: akka
      port: 2552
      targetPort: 2552
    - name: akka-management
      port: 8558
      targetPort: 8558
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: ws
      port: 9090
      targetPort: 9090
  selector:
    app: live
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: live-grpc
spec:
  grpc: True
  prefix: /
  service: live:8080
  timeout_ms: 0
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: live-ws
spec:
  use_websocket: true
  prefix: /ws
  service: live:9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
spec:
  replicas: 2
  selector:
    matchLabels:
      app: live
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
        - name: live
          image: live:0.1
          imagePullPolicy: Never
          env:
            - name: ENV
              value: kubernetes
          ports:
            - name: remoting
              containerPort: 2552
            - name: management
              containerPort: 8558
            - name: grpc
              containerPort: 8080
            - name: ws
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            initialDelaySeconds: 15